// --- NEO4J CYPHER INJECTION FOR MIS SPINE SURGERY ---
MERGE (d:Doctor {name: 'Dr. Choi', title: 'CEO & Spine Surgeon', clinic: 'Namyangju Baek Hospital (NDB)'})
MERGE (s:Specialty {name: 'MIS Spine Surgery', full_name: 'Minimally Invasive Spine Surgery'})
MERGE (d)-[:SPECIALIZES_IN]->(s)
MERGE (w:WikiNode {name: 'AR_VR_MR_and_AI_in_Spine'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Complications_and_Dural_Tears'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Endoscopic_Spine_Surgery'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Index'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Innovations_and_Biomaterials'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Kambin_Triangle'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'MIS_TLIF_and_CBT'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Motion_Preservation_TDR'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'OLIF_LLIF_ALIF_OLIF51'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Spine_Deformity_and_cMIS'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Spine_Navigation_and_Robotics'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (w:WikiNode {name: 'Uniportal_vs_Biportal_UBE'})
MERGE (s)-[:HAS_WIKI_NODE]->(w)
MERGE (c:Chapter {filename: 'Chapter_01_History_and_Progress_of_Minimally_Invasive_Spine_Surgery'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_02_Overview_of_Minimally_Invasive_Spine_Surgery'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_03_Clinical_Evidence_of_Minimally_Invasive_Spine_Surgery_A_Revi'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_04_Basic_Set_Up_of_Full_Endoscopic_Spine_Surgery'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_05_Transforaminal_Endoscopic_Discectomy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_06_Interlaminar_Endoscopic_Lumbar_Discectomy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_07_Interlaminar_Endoscopic_Decompression_for_Central_Stenosis'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_08_Endoscopic_Spinal_Decompression_for_Lumbar_Spinal_Stenosis'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_09_Microendoscopic_Lumbar_Interbody_Fusion_MELIF'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_10_Unilateral_Biportal_Endoscopic_Transforaminal_Lumbar_Interbo'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_11_PETLIF_Percutaneous_Endoscopic_Transforaminal_Lumbar_Interbo'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_12_Transforaminal_Endoscopic_Thoracic_Discectomy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_13_Endoscopic_Decompression_of_Thoracic_Myelopathy_Due_to_Thora'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_14_Cervical_Microendoscopic_Foraminotomy_MEF_and_Microendoscopi'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_15_Anterior_Endoscopic_Cervical_Discectomy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_16_Posterior_Endoscopic_Cervical_Foraminotomy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_17_Complications_and_Management_in_Endoscopic_Spine_Surgery'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_18_Complication_and_Prevention_of_Unilateral_Biportal_Endoscopy'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_19_Clinical_Impact_of_Muscle_Sparing_Wiltse_Transforaminal_Lumb'})
MERGE (s)-[:HAS_CHAPTER]->(c)
MERGE (c:Chapter {filename: 'Chapter_20_MIS_TLIF_in_High_Grade_Spondylolisthesis'})
MERGE (s)-[:HAS_CHAPTER]->(c)